# Generated by Django 5.0.6 on 2024-06-14 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_title', models.CharField(max_length=200, unique=True)),
                ('syllabus_slug', models.SlugField(max_length=200, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('deadline_official', models.DateTimeField(auto_now_add=True)),
                ('status_syllabus', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_instance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_title', models.CharField(max_length=200, unique=True)),
                ('module_slug', models.SlugField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=200, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status_syllabus', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('syllabus_slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_instance', to='textbook.syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_title', models.CharField(max_length=200, unique=True)),
                ('unit_slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=200, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=200, unique=True)),
                ('status_syllabus', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('module_slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_instance', to='textbook.module')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_set', models.DateTimeField(auto_now_add=True)),
                ('pace_set', models.DateTimeField(auto_now_add=True)),
                ('pace_you', models.DateTimeField(auto_now_add=True)),
                ('last_visited', models.DateTimeField(auto_now_add=True)),
                ('been_here', models.BooleanField(max_length=200, unique=True)),
                ('read', models.BooleanField(max_length=200, unique=True)),
                ('understood', models.BooleanField(max_length=200, unique=True)),
                ('bookmark', models.BooleanField(max_length=200, unique=True)),
                ('user_notes', models.CharField(max_length=200, unique=True)),
                ('highlights', models.CharField(max_length=200, unique=True)),
                ('unit_feedback', models.CharField(max_length=200, unique=True)),
                ('unit_slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress_instance', to='textbook.unit')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress_instance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
