# Generated by Django 5.0.6 on 2024-06-14 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='syllabus_slug',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='module_slug',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='unit_slug',
        ),
        migrations.AddField(
            model_name='module',
            name='module_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='syllabus_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_module', to='textbook.syllabus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='syllabus_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='module_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='module_unit', to='textbook.module'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprogress',
            name='unit_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='unit_user_progress', to='textbook.unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_user_progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
