# Generated by Django 5.0.6 on 2024-06-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0002_remove_module_syllabus_slug_remove_unit_module_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='module_id',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='syllabus_id',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_id',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='module',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='unit',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='unit',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='unit',
            name='content',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='been_here',
            field=models.BooleanField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='bookmark',
            field=models.BooleanField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='highlights',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='read',
            field=models.BooleanField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='understood',
            field=models.BooleanField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='unit_feedback',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user_notes',
            field=models.CharField(max_length=200),
        ),
    ]
