# Generated by Django 5.0.6 on 2024-06-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0003_remove_module_module_id_remove_syllabus_syllabus_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='status_syllabus',
            new_name='status_module',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='status_syllabus',
            new_name='status_unit',
        ),
    ]
