# Generated by Django 5.0.6 on 2024-07-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0007_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
