# Generated by Django 5.0.6 on 2024-11-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0009_alter_userprogress_been_here_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='bookmark',
            field=models.BooleanField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='read',
            field=models.BooleanField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='understood',
            field=models.BooleanField(max_length=200),
        ),
        migrations.DeleteModel(
            name='UnitProgress',
        ),
    ]
