# Generated by Django 5.0.6 on 2024-11-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0012_checkboxstate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckboxState',
        ),
    ]
